
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

import logic.*;
import java_cup.runtime.Symbol;
import java.util.LinkedList;
import com.mycompany.practica1.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class S_Analyzer extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Symbols.class;
}

  /** Default constructor. */
  @Deprecated
  public S_Analyzer() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public S_Analyzer(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public S_Analyzer(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\027\000\002\002\004\000\002\002\005\000\002\002" +
    "\005\000\002\002\005\000\002\002\005\000\002\011\002" +
    "\000\002\002\006\000\002\002\003\000\002\003\017\000" +
    "\002\003\017\000\002\003\021\000\002\003\021\000\002" +
    "\003\004\000\002\004\023\000\002\004\004\000\002\005" +
    "\004\000\002\005\004\000\002\006\020\000\002\006\004" +
    "\000\002\007\003\000\002\007\002\000\002\010\003\000" +
    "\002\010\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\006\003\004\012\007\001\002\000\006\003" +
    "\004\012\007\001\002\000\004\002\162\001\002\000\004" +
    "\013\144\001\002\000\016\003\011\017\015\020\014\021" +
    "\012\022\010\023\013\001\002\000\004\010\126\001\002" +
    "\000\016\003\011\017\015\020\014\021\012\022\010\023" +
    "\013\001\002\000\004\010\106\001\002\000\004\010\066" +
    "\001\002\000\004\010\052\001\002\000\004\010\020\001" +
    "\002\000\004\013\ufff1\001\002\000\004\013\ufff2\001\002" +
    "\000\004\024\021\001\002\000\004\027\022\001\002\000" +
    "\006\010\025\026\024\001\002\000\014\004\033\005\031" +
    "\006\032\007\030\027\041\001\002\000\016\004\ufffa\005" +
    "\ufffa\006\ufffa\007\ufffa\011\ufffa\027\ufffa\001\002\000\006" +
    "\010\025\026\024\001\002\000\014\004\033\005\031\006" +
    "\032\007\030\011\ufffc\001\002\000\004\011\040\001\002" +
    "\000\006\010\025\026\024\001\002\000\006\010\025\026" +
    "\024\001\002\000\006\010\025\026\024\001\002\000\006" +
    "\010\025\026\024\001\002\000\016\004\000\005\000\006" +
    "\032\007\030\011\000\027\000\001\002\000\016\004\ufffd" +
    "\005\ufffd\006\ufffd\007\ufffd\011\ufffd\027\ufffd\001\002\000" +
    "\016\004\uffff\005\uffff\006\032\007\030\011\uffff\027\uffff" +
    "\001\002\000\016\004\ufffe\005\ufffe\006\ufffe\007\ufffe\011" +
    "\ufffe\027\ufffe\001\002\000\016\004\ufffb\005\ufffb\006\ufffb" +
    "\007\ufffb\011\ufffb\027\ufffb\001\002\000\006\010\025\026" +
    "\024\001\002\000\014\004\033\005\031\006\032\007\030" +
    "\027\043\001\002\000\006\010\025\026\024\001\002\000" +
    "\014\004\033\005\031\006\032\007\030\027\045\001\002" +
    "\000\004\025\046\001\002\000\004\011\047\001\002\000" +
    "\006\012\007\013\uffed\001\002\000\004\013\ufff9\001\002" +
    "\000\004\013\uffee\001\002\000\004\024\053\001\002\000" +
    "\004\027\054\001\002\000\006\010\025\026\024\001\002" +
    "\000\014\004\033\005\031\006\032\007\030\027\056\001" +
    "\002\000\006\010\025\026\024\001\002\000\014\004\033" +
    "\005\031\006\032\007\030\027\060\001\002\000\006\010" +
    "\025\026\024\001\002\000\014\004\033\005\031\006\032" +
    "\007\030\027\062\001\002\000\004\025\063\001\002\000" +
    "\004\011\064\001\002\000\006\012\007\013\uffed\001\002" +
    "\000\004\013\ufff8\001\002\000\004\024\067\001\002\000" +
    "\004\027\070\001\002\000\006\010\025\026\024\001\002" +
    "\000\014\004\033\005\031\006\032\007\030\027\072\001" +
    "\002\000\006\010\025\026\024\001\002\000\014\004\033" +
    "\005\031\006\032\007\030\027\074\001\002\000\006\010" +
    "\025\026\024\001\002\000\014\004\033\005\031\006\032" +
    "\007\030\027\076\001\002\000\006\010\025\026\024\001" +
    "\002\000\014\004\033\005\031\006\032\007\030\027\100" +
    "\001\002\000\006\010\025\026\024\001\002\000\014\004" +
    "\033\005\031\006\032\007\030\027\102\001\002\000\004" +
    "\025\103\001\002\000\004\011\104\001\002\000\006\012" +
    "\007\013\uffed\001\002\000\004\013\ufff4\001\002\000\004" +
    "\024\107\001\002\000\004\027\110\001\002\000\006\010" +
    "\025\026\024\001\002\000\014\004\033\005\031\006\032" +
    "\007\030\027\112\001\002\000\006\010\025\026\024\001" +
    "\002\000\014\004\033\005\031\006\032\007\030\027\114" +
    "\001\002\000\006\010\025\026\024\001\002\000\014\004" +
    "\033\005\031\006\032\007\030\027\116\001\002\000\006" +
    "\010\025\026\024\001\002\000\014\004\033\005\031\006" +
    "\032\007\030\027\120\001\002\000\004\025\121\001\002" +
    "\000\004\011\122\001\002\000\006\012\007\013\uffed\001" +
    "\002\000\004\013\ufff7\001\002\000\004\013\ufff3\001\002" +
    "\000\004\013\ufff5\001\002\000\004\024\127\001\002\000" +
    "\004\027\130\001\002\000\006\010\025\026\024\001\002" +
    "\000\014\004\033\005\031\006\032\007\030\027\132\001" +
    "\002\000\006\010\025\026\024\001\002\000\014\004\033" +
    "\005\031\006\032\007\030\027\134\001\002\000\006\010" +
    "\025\026\024\001\002\000\014\004\033\005\031\006\032" +
    "\007\030\027\136\001\002\000\006\010\025\026\024\001" +
    "\002\000\014\004\033\005\031\006\032\007\030\027\140" +
    "\001\002\000\004\025\141\001\002\000\004\011\142\001" +
    "\002\000\006\012\007\013\uffed\001\002\000\004\013\ufff6" +
    "\001\002\000\004\014\145\001\002\000\004\015\146\001" +
    "\002\000\004\010\147\001\002\000\004\016\150\001\002" +
    "\000\004\027\151\001\002\000\006\010\025\026\024\001" +
    "\002\000\014\004\033\005\031\006\032\007\030\027\153" +
    "\001\002\000\006\010\025\026\024\001\002\000\014\004" +
    "\033\005\031\006\032\007\030\027\155\001\002\000\006" +
    "\010\025\026\024\001\002\000\014\004\033\005\031\006" +
    "\032\007\030\011\157\001\002\000\010\002\uffeb\003\004" +
    "\012\007\001\002\000\004\002\ufff0\001\002\000\004\002" +
    "\uffec\001\002\000\004\002\001\001\002\000\004\002\uffef" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\161\000\006\005\005\006\004\001\001\000\006\005" +
    "\005\006\162\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\016\004\015\001\001\000\002\001\001\000" +
    "\006\003\124\004\123\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\002\022\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\002\025\001\001\000\004\011\026\001\001" +
    "\000\002\001\001\000\004\002\036\001\001\000\004\002" +
    "\035\001\001\000\004\002\034\001\001\000\004\002\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\002\041" +
    "\001\001\000\002\001\001\000\004\002\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\050\007\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\002\054" +
    "\001\001\000\002\001\001\000\004\002\056\001\001\000" +
    "\002\001\001\000\004\002\060\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\005\050\007" +
    "\064\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\002\070\001\001\000\002\001\001\000" +
    "\004\002\072\001\001\000\002\001\001\000\004\002\074" +
    "\001\001\000\002\001\001\000\004\002\076\001\001\000" +
    "\002\001\001\000\004\002\100\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\005\050\007" +
    "\104\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\002\110\001\001\000\002\001\001\000" +
    "\004\002\112\001\001\000\002\001\001\000\004\002\114" +
    "\001\001\000\002\001\001\000\004\002\116\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\050\007\122\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\002\130\001\001\000\002\001\001\000\004\002" +
    "\132\001\001\000\002\001\001\000\004\002\134\001\001" +
    "\000\002\001\001\000\004\002\136\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\050" +
    "\007\142\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\002\151\001\001\000\002\001\001\000" +
    "\004\002\153\001\001\000\002\001\001\000\004\002\155" +
    "\001\001\000\002\001\001\000\010\005\005\006\160\010" +
    "\157\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$S_Analyzer$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$S_Analyzer$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$S_Analyzer$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public String result="";

    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {        
        String lexeme = s.value.toString();
        String description = "";
        int line = s.right;
        int column = s.left;
        int tipo = s.sym;
        
        System.out.println("! Error Sintactico Recuperado !");
        System.out.println("\t\tLexema: "+ lexeme);
        System.out.println("\t\tFila: "+ line);
        System.out.println("\t\tColumna: "+ column);
        System.out.println("\t\tVariable tipo: " + tipo);

        switch(tipo){
            case 2:
                description = "Se esperaba un número antes del '+'";
                break;
            case 3:
                description = "Se esperaba un número antes del '-'";
                break;
            case 4:
                description = "Se esperaba un número antes del '*'";
                break;
            case 5:
                description = "Se esperaba un '('";
                break;
            case 6:
                description = "Se esperaba una figura o 'anterior'";
                break;
            case 7:
                description = "Se esperaba un color o número";
                break;
            case 8:
                description = "Se esperaba un ')'";
                break;
            case 9:
                description = "Instrucción sin objetos anteriores";
                break;
            case 10:
                description = "Se esperaba la palabra 'animar'";
                break;
            case 11:
                description = "Se esperaba la palabra 'objeto'";
                break;
            case 12:
                description = "Se esperaba un '('";
                break;
            case 17:
                description = "Se esperaba la palabra 'graficar'";
                break;
            case 18:
                description = "Se esperaba un '('";
                break;
            case 20:
                description = "Se esperaba una coma ' , '";
            case 21:
                description = "Se esperaba un nombre o número";
                break;
            case 25:
                description = "Se esperaba 'curva' o 'línea'";
                break;
            default:
                System.out.println("Es otro error");
                description = "Caracter no esperado";
        }

        TError data = new TError(lexeme,line,column,"Sintactico",description);
        errorReport.TableErrors.add(data);
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {        
        String lexeme = s.value.toString();
        int line = s.right;
        int column = s.left;
        
        System.out.println("! Error Sintactico, PANIC MODE ! ");
        System.out.println("\t\tLexema: "+lexeme);
        System.out.println("\t\tFila: "+line);
        System.out.println("\t\tColumna: "+column);

        TError data = new TError(lexeme,line,column,"Sintactico","Caracter no esperado");
        errorReport.TableErrors.add(data);
     
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$S_Analyzer$actions {



  private final S_Analyzer parser;

  /** Constructor */
  CUP$S_Analyzer$actions(S_Analyzer parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$S_Analyzer$do_action_part00000000(
    int                        CUP$S_Analyzer$act_num,
    java_cup.runtime.lr_parser CUP$S_Analyzer$parser,
    java.util.Stack            CUP$S_Analyzer$stack,
    int                        CUP$S_Analyzer$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$S_Analyzer$result;

      /* select the action based on the action number */
      switch (CUP$S_Analyzer$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= F EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).value;
		RESULT = start_val;
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$S_Analyzer$parser.done_parsing();
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // A ::= A plus A 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
		double val1= Double.parseDouble(a);
                    double val2= Double.parseDouble(b);
                    double r = val1+val2;
                    RESULT = String.valueOf(r);
                    String ocurrency = String.valueOf(a) + " + " + String.valueOf(b);
                    int line = cur_token.right;
                    int column = cur_token.left;
                    TTokens data = new TTokens("Suma", ocurrency, line, column);
                    reports.TokensList.add(data);
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("A",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // A ::= A minus A 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
		double val1= Double.parseDouble(a);
                    double val2= Double.parseDouble(b);
                    double r = val1-val2;
                    RESULT = String.valueOf(r);
                    String ocurrency = String.valueOf(a) + " - " + String.valueOf(b);
                    int line = cur_token.right;
                    int column = cur_token.left;
                    TTokens data = new TTokens("Resta", ocurrency, line, column);
                    reports.TokensList.add(data); 
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("A",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // A ::= A split A 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
		double val1= Double.parseDouble(a);
                    double val2= Double.parseDouble(b);
                    double r = val1/val2;
                    RESULT = String.valueOf(r);
                    String ocurrency = String.valueOf(a) + " / " + String.valueOf(b);
                    int line = cur_token.right;
                    int column = cur_token.left;
                    TTokens data = new TTokens("División", ocurrency, line, column);
                    reports.TokensList.add(data); 
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("A",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // A ::= A times A 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
		double val1= Double.parseDouble(a);
                    double val2= Double.parseDouble(b);
                    double r = val1*val2;
                    RESULT = String.valueOf(r); 
                    String ocurrency = String.valueOf(a) + " * " + String.valueOf(b);
                    int line = cur_token.right;
                    int column = cur_token.left;
                    TTokens data = new TTokens("Multiplicación", ocurrency, line, column);
                    reports.TokensList.add(data);
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("A",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$0 ::= 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
 RESULT = a; 
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("NT$0",7, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // A ::= paro A NT$0 parc 
            {
              String RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("A",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-3)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // A ::= num 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.peek()).value;
		 RESULT = a; 
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("A",0, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // B ::= circle paro name comma A comma A comma A comma color parc G 
            {
              String RESULT =null;
		int nameObjectleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).left;
		int nameObjectright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).right;
		Object nameObject = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).value;
		int posxleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).left;
		int posxright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).right;
		String posx = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).value;
		int posyleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).left;
		int posyright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).right;
		String posy = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).value;
		int numbOneleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).left;
		int numbOneright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).right;
		String numbOne = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).value;
		int colorsleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int colorsright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		Object colors = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		System.out.println("Cadena aceptada (Circulo)");
      reports.ObjectsList.add("circulo");
      reports.ColorsList.add(String.valueOf(colors));
      String name = String.valueOf(nameObject);
      String color = String.valueOf(colors);
      double px = Double.parseDouble(posx);
      double py = Double.parseDouble(posy);
      double radius = Double.parseDouble(numbOne);
      circle data = new circle(name, color, px, py, radius);
      shapes.circleShapes.add(data);
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("B",1, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // B ::= square paro name comma A comma A comma A comma color parc G 
            {
              String RESULT =null;
		int nameObjectleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).left;
		int nameObjectright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).right;
		Object nameObject = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).value;
		int posxleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).left;
		int posxright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).right;
		String posx = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).value;
		int posyleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).left;
		int posyright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).right;
		String posy = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).value;
		int numbOneleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).left;
		int numbOneright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).right;
		String numbOne = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).value;
		int colorsleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int colorsright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		Object colors = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		System.out.println("Cadena aceptada (Cuadrado)");
      reports.ObjectsList.add("cuadrado");
      reports.ColorsList.add(String.valueOf(colors));
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("B",1, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // B ::= rectangle paro name comma A comma A comma A comma A comma color parc G 
            {
              String RESULT =null;
		int nameObjectleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)).left;
		int nameObjectright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)).right;
		Object nameObject = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)).value;
		int posxleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).left;
		int posxright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).right;
		String posx = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).value;
		int posyleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).left;
		int posyright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).right;
		String posy = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).value;
		int numbOneleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).left;
		int numbOneright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).right;
		String numbOne = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).value;
		int numbTwoleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).left;
		int numbTworight = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).right;
		String numbTwo = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).value;
		int colorsleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int colorsright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		Object colors = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		System.out.println("Cadena aceptada (Rectangulo)");
      reports.ObjectsList.add("rectangulo");
      reports.ColorsList.add(String.valueOf(colors));
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("B",1, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-14)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // B ::= line paro name comma A comma A comma A comma A comma color parc G 
            {
              String RESULT =null;
		int nameObjectleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)).left;
		int nameObjectright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)).right;
		Object nameObject = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-12)).value;
		int posxleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).left;
		int posxright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).right;
		String posx = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-10)).value;
		int posyleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).left;
		int posyright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).right;
		String posy = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).value;
		int numbOneleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).left;
		int numbOneright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).right;
		String numbOne = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-6)).value;
		int numbTwoleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).left;
		int numbTworight = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).right;
		String numbTwo = (String)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-4)).value;
		int colorsleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int colorsright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		Object colors = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		System.out.println("Cadena aceptada (Linea)");
      reports.ObjectsList.add("linea");
      reports.ColorsList.add(String.valueOf(colors));
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("B",1, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-14)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // B ::= error B 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("B",1, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // C ::= polygon paro name comma A comma A comma A comma A comma A comma color parc G 
            {
              String RESULT =null;
		int colorsleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).left;
		int colorsright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).right;
		Object colors = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-2)).value;
		System.out.println("Cadena aceptada (Poligono)");
       reports.ObjectsList.add("poligono");
       reports.ColorsList.add(String.valueOf(colors));
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("C",2, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-16)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // C ::= error C 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("C",2, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // E ::= graph B 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("E",3, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // E ::= graph C 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("E",3, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // F ::= E animate object previous paro animation comma A comma A comma A parc H 
            {
              String RESULT =null;
		int animleft = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).left;
		int animright = ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).right;
		Object anim = (Object)((java_cup.runtime.Symbol) CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-8)).value;
		System.out.println("Instrucciones completas correctas");
      reports.AnimationsList.add(String.valueOf(anim));
              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("F",4, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-13)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // F ::= error F 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("F",4, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.elementAt(CUP$S_Analyzer$top-1)), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // G ::= E 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("G",5, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // G ::= 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("G",5, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // H ::= F 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("H",6, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // H ::= 
            {
              String RESULT =null;

              CUP$S_Analyzer$result = parser.getSymbolFactory().newSymbol("H",6, ((java_cup.runtime.Symbol)CUP$S_Analyzer$stack.peek()), RESULT);
            }
          return CUP$S_Analyzer$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$S_Analyzer$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$S_Analyzer$do_action(
    int                        CUP$S_Analyzer$act_num,
    java_cup.runtime.lr_parser CUP$S_Analyzer$parser,
    java.util.Stack            CUP$S_Analyzer$stack,
    int                        CUP$S_Analyzer$top)
    throws java.lang.Exception
    {
              return CUP$S_Analyzer$do_action_part00000000(
                               CUP$S_Analyzer$act_num,
                               CUP$S_Analyzer$parser,
                               CUP$S_Analyzer$stack,
                               CUP$S_Analyzer$top);
    }
}

}
