
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int parc = 7;
  public static final int graph = 8;
  public static final int minus = 3;
  public static final int previous = 11;
  public static final int animate = 9;
  public static final int num = 18;
  public static final int shapesone = 13;
  public static final int times = 4;
  public static final int EOF = 0;
  public static final int shapesthree = 15;
  public static final int split = 5;
  public static final int color = 17;
  public static final int error = 1;
  public static final int paro = 6;
  public static final int plus = 2;
  public static final int animation = 12;
  public static final int comma = 19;
  public static final int object = 10;
  public static final int shapestwo = 14;
  public static final int name = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "plus",
  "minus",
  "times",
  "split",
  "paro",
  "parc",
  "graph",
  "animate",
  "object",
  "previous",
  "animation",
  "shapesone",
  "shapestwo",
  "shapesthree",
  "name",
  "color",
  "num",
  "comma"
  };
}

