
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int name = 9;
  public static final int times = 4;
  public static final int lineterminator = 8;
  public static final int minus = 3;
  public static final int paro = 6;
  public static final int num = 11;
  public static final int EOF = 0;
  public static final int plus = 2;
  public static final int split = 5;
  public static final int error = 1;
  public static final int colorprueba = 10;
  public static final int parc = 7;
  public static final int comma = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "plus",
  "minus",
  "times",
  "split",
  "paro",
  "parc",
  "lineterminator",
  "name",
  "colorprueba",
  "num",
  "comma"
  };
}

